CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TYPE public.approval_status AS ENUM ('Чернетка', 'Надіслано', 'Схвалено', 'Відхилено');
CREATE TYPE public.case_status AS ENUM ('Відкрито', 'Закрито', 'Призупинено');
CREATE TYPE public.detective_status AS ENUM ('Активний(а)', 'У відпустці', 'У відставці', 'Звільнений(а)');
CREATE TYPE public.evidence_type AS ENUM ('Біометричний доказ', 'Біологічний доказ', 'Відеодоказ', 'Фотодоказ', 'Матеріальний доказ', 'Цифровий доказ', 'Документальний доказ', 'Аудіодоказ', 'Фізичний доказ', 'Електронний доказ', 'Інше');

CREATE TABLE case_type (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    CONSTRAINT "PK_case_type" PRIMARY KEY (id),
    CONSTRAINT name_format CHECK (name ~ '^[А-ЯІЇЄа-яіїє0-9\s\-.,:;/]+$'),
    CONSTRAINT price_format CHECK (price > 0)
);

CREATE TABLE client (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    apartment_number integer,
    building_number character varying(30) NOT NULL,
    city character varying(30) NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(100) NOT NULL,
    father_name character varying(100),
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone_number character varying(20) NOT NULL,
    region character varying(30) NOT NULL,
    registration_date timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    street character varying(50) NOT NULL,
    CONSTRAINT "PK_client" PRIMARY KEY (id),
    CONSTRAINT apartment_number_format CHECK (apartment_number IS NULL OR apartment_number > 0),
    CONSTRAINT building_number_format CHECK (building_number ~ '^[0-9/]+$'),
    CONSTRAINT city_format CHECK (city ~ '^[А-ЯІЇЄа-яіїє\-]+$'),
    CONSTRAINT date_of_birth_format CHECK (date_of_birth <= CURRENT_DATE),
    CONSTRAINT email_format CHECK (email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT name_format CHECK (first_name ~ '^[А-ЯІЇЄа-яіїє]+$' AND last_name ~ '^[А-ЯІЇЄа-яіїє]+$' AND (father_name IS NULL OR father_name ~ '^[А-ЯІЇЄа-яіїє]+$')),
    CONSTRAINT phone_number_format CHECK (phone_number ~ '^\+380\d{9}$'),
    CONSTRAINT region_format CHECK (region ~ '^[А-ЯІЇЄа-яіїє]+$'),
    CONSTRAINT registration_date_format CHECK (registration_date <= CURRENT_TIMESTAMP),
    CONSTRAINT street_format CHECK (street ~ '^[А-ЯІЇЄа-яіїє\s\-]+$')
);

CREATE TABLE detective (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    father_name character varying(100),
    phone_number character varying(20) NOT NULL,
    email character varying(100) NOT NULL,
    date_of_birth date NOT NULL,
    region character varying(30) NOT NULL,
    city character varying(30) NOT NULL,
    street character varying(50) NOT NULL,
    building_number character varying(30) NOT NULL,
    apartment_number integer,
    hire_date date NOT NULL,
    salary numeric(10,2) NOT NULL,
    personal_notes text,
    status detective_status NOT NULL DEFAULT 'Активний(а)',
    CONSTRAINT "PK_detective" PRIMARY KEY (id),
    CONSTRAINT apartment_number_format CHECK (apartment_number IS NULL OR apartment_number > 0),
    CONSTRAINT building_number_format CHECK (building_number ~ '^[0-9/]+$'),
    CONSTRAINT city_format CHECK (city ~ '^[А-ЯІЇЄа-яіїє\-]+$'),
    CONSTRAINT date_of_birth_format CHECK (date_of_birth <= CURRENT_DATE),
    CONSTRAINT detective_hire_date_format CHECK (hire_date <= CURRENT_DATE),
    CONSTRAINT detective_salary_format CHECK (salary >= 0),
    CONSTRAINT email_format CHECK (email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT name_format CHECK (first_name ~ '^[А-ЯІЇЄа-яіїє]+$' AND last_name ~ '^[А-ЯІЇЄа-яіїє]+$' AND (father_name IS NULL OR father_name ~ '^[А-ЯІЇЄа-яіїє]+$')),
    CONSTRAINT phone_number_format CHECK (phone_number ~ '^\+380\d{9}$'),
    CONSTRAINT region_format CHECK (region ~ '^[А-ЯІЇЄа-яіїє]+$'),
    CONSTRAINT street_format CHECK (street ~ '^[А-ЯІЇЄа-яіїє\s\-]+$')
);

CREATE TABLE evidence (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    description character varying(200) NOT NULL,
    type evidence_type NOT NULL,
    collection_date timestamp with time zone NOT NULL,
    region character varying(200) NOT NULL DEFAULT 'Не вказано',
    annotation character varying(200),
    purpose character varying(200),
    CONSTRAINT "PK_evidence" PRIMARY KEY (id),
    CONSTRAINT collection_date_format CHECK (collection_date <= CURRENT_TIMESTAMP)
);

CREATE TABLE suspect (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(100),
    last_name character varying(100),
    father_name character varying(100),
    nickname character varying(50),
    phone_number character varying(20),
    date_of_birth date,
    region character varying(30),
    city character varying(30),
    street character varying(50),
    building_number character varying(30),
    apartment_number integer,
    height integer,
    weight integer,
    physical_description text,
    prior_convictions text,
    CONSTRAINT "PK_suspect" PRIMARY KEY (id),
    CONSTRAINT apartment_number_format CHECK (apartment_number IS NULL OR apartment_number > 0),
    CONSTRAINT building_number_format CHECK (building_number ~ '^[0-9/]+$'),
    CONSTRAINT city_format CHECK (city ~ '^[А-ЯІЇЄа-яіїє\-]+$'),
    CONSTRAINT date_of_birth_format CHECK (date_of_birth <= CURRENT_DATE),
    CONSTRAINT name_format CHECK (first_name ~ '^[А-ЯІЇЄа-яіїє]+$' AND last_name ~ '^[А-ЯІЇЄа-яіїє]+$' AND (father_name IS NULL OR father_name ~ '^[А-ЯІЇЄа-яіїє]+$')),
    CONSTRAINT phone_number_format CHECK (phone_number ~ '^\+380\d{9}$'),
    CONSTRAINT region_format CHECK (region ~ '^[А-ЯІЇЄа-яіїє]+$'),
    CONSTRAINT street_format CHECK (street ~ '^[А-ЯІЇЄа-яіїє\s\-]+$'),
    CONSTRAINT weight_height_format CHECK (weight IS NOT NULL AND weight > 0 AND height IS NOT NULL AND height > 0 OR weight IS NULL AND height IS NULL)
);

CREATE TABLE "case" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    case_type_id integer NOT NULL,
    client_id integer NOT NULL,
    detective_id integer,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    start_date date NOT NULL DEFAULT (CURRENT_DATE),
    deadline_date date NOT NULL,
    close_date date,
    status case_status NOT NULL DEFAULT 'Відкрито',
    CONSTRAINT "PK_case" PRIMARY KEY (id),
    CONSTRAINT close_date_format CHECK (close_date IS NULL OR close_date >= start_date),
    CONSTRAINT deadline_format CHECK (deadline_date >= start_date),
    CONSTRAINT "FK_case_case_type_id" FOREIGN KEY (case_type_id) REFERENCES case_type (id),
    CONSTRAINT "FK_case_client_id" FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT "FK_case_detective_id" FOREIGN KEY (detective_id) REFERENCES detective (id)
);

CREATE TABLE case_evidence (
    evidence_id integer NOT NULL,
    case_id integer NOT NULL,
    approval_status approval_status NOT NULL DEFAULT 'Чернетка',
    CONSTRAINT "PK_case_evidence" PRIMARY KEY (evidence_id, case_id),
    CONSTRAINT "FK_case_evidence_case_id" FOREIGN KEY (case_id) REFERENCES "case" (id),
    CONSTRAINT "FK_case_evidence_suspect_id" FOREIGN KEY (evidence_id) REFERENCES evidence (id)
);

CREATE TABLE case_suspect (
    suspect_id integer NOT NULL,
    case_id integer NOT NULL,
    is_interrogated boolean NOT NULL,
    alibi text,
    approval_status approval_status NOT NULL DEFAULT 'Чернетка',
    CONSTRAINT "PK_case_suspect" PRIMARY KEY (suspect_id, case_id),
    CONSTRAINT "FK_case_suspect_case_id" FOREIGN KEY (case_id) REFERENCES "case" (id),
    CONSTRAINT "FK_case_suspect_suspect_id" FOREIGN KEY (suspect_id) REFERENCES suspect (id)
);

CREATE TABLE expense (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    case_id integer NOT NULL,
    date_time timestamp with time zone NOT NULL,
    purpose character varying(255) NOT NULL,
    amount numeric(10,2) NOT NULL,
    annotation text,
    approval_status approval_status NOT NULL DEFAULT 'Чернетка',
    CONSTRAINT "PK_expense" PRIMARY KEY (id),
    CONSTRAINT amount_format CHECK (amount > 0),
    CONSTRAINT date_time_format CHECK (date_time <= CURRENT_TIMESTAMP),
    CONSTRAINT purpose_format CHECK (purpose ~ '^[А-ЯІЇЄа-яіїєA-Za-z0-9\s\-\.,:;’]+$'),
    CONSTRAINT expense_case_id_fk FOREIGN KEY (case_id) REFERENCES "case" (id)
);

CREATE TABLE report (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    case_id integer NOT NULL,
    report_date timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    summary text NOT NULL,
    comments text,
    approval_status approval_status NOT NULL DEFAULT 'Чернетка',
    CONSTRAINT "PK_report" PRIMARY KEY (id),
    CONSTRAINT date_format CHECK (report_date <= CURRENT_TIMESTAMP),
    CONSTRAINT "FK_report_case_id" FOREIGN KEY (case_id) REFERENCES "case" (id)
);

CREATE INDEX "IX_case_case_type_id" ON "case" (case_type_id);

CREATE INDEX "IX_case_client_id" ON "case" (client_id);

CREATE INDEX "IX_case_detective_id" ON "case" (detective_id);

CREATE INDEX "IX_case_evidence_case_id" ON case_evidence (case_id);

CREATE INDEX "IX_case_suspect_case_id" ON case_suspect (case_id);

CREATE INDEX "IX_expense_case_id" ON expense (case_id);

CREATE INDEX "IX_report_case_id" ON report (case_id);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "Role" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT created_at_format CHECK ("CreatedAt" <= CURRENT_TIMESTAMP),
    CONSTRAINT email_format CHECK ("Email" ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT last_login_at_format CHECK ("LastLoginAt" IS NULL OR "LastLoginAt" <= CURRENT_TIMESTAMP),
    CONSTRAINT role_format CHECK ("Role" IN ('Admin', 'Detective')),
    CONSTRAINT username_format CHECK ("Username" ~ '^[a-zA-Z0-9_]+$')
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250601113931_InitialCreate', '9.0.10');

ALTER TABLE suspect ADD approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status;

ALTER TABLE report ALTER COLUMN approval_status SET DEFAULT 'Чернетка'::approval_status;

ALTER TABLE expense ALTER COLUMN approval_status SET DEFAULT 'Чернетка'::approval_status;

ALTER TABLE evidence ADD approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status;

ALTER TABLE detective ALTER COLUMN status SET DEFAULT 'Активний(а)'::detective_status;

ALTER TABLE detective ALTER COLUMN hire_date TYPE timestamp with time zone;
ALTER TABLE detective ALTER COLUMN hire_date SET DEFAULT (CURRENT_TIMESTAMP);

ALTER TABLE case_suspect ALTER COLUMN approval_status SET DEFAULT 'Чернетка'::approval_status;

ALTER TABLE case_evidence ALTER COLUMN approval_status SET DEFAULT 'Чернетка'::approval_status;

ALTER TABLE "case" ALTER COLUMN status SET DEFAULT 'Відкрито'::case_status;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251020164357_AddApprovalStatusToSuspectAndEvidence', '9.0.10');

ALTER TABLE detective DROP CONSTRAINT detective_hire_date_format;

ALTER TABLE detective ADD CONSTRAINT detective_hire_date_format CHECK (hire_date::date <= CURRENT_DATE);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260107131259_FixDetectiveHireDateConstraint', '9.0.10');

COMMIT;

