GET http://localhost:5041/clients

###
GET http://localhost:5041/clients/5

###
POST http://localhost:5041/clients
Content-Type: application/json

{
  "FirstName" : "Natalya",
  "LastName" : "Kovalova",
  "FatherName" : "Serhiivna"
}

###
PUT http://localhost:5041/clients/2
Content-Type: application/json

{
  "LastName" : "Bocharov",
  "FatherName" : "Godzilovich"
}

###
DELETE http://localhost:5041/clients/1
