-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Username" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public."case"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    case_type_id integer NOT NULL,
    client_id integer NOT NULL,
    detective_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL DEFAULT CURRENT_DATE,
    deadline_date date NOT NULL,
    close_date date,
    status case_status NOT NULL DEFAULT 'Відкрито'::case_status,
    CONSTRAINT "PK_case" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.case_evidence
(
    evidence_id integer NOT NULL,
    case_id integer NOT NULL,
    approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status,
    CONSTRAINT "PK_case_evidence" PRIMARY KEY (evidence_id, case_id)
);

CREATE TABLE IF NOT EXISTS public.case_suspect
(
    suspect_id integer NOT NULL,
    case_id integer NOT NULL,
    is_interrogated boolean NOT NULL,
    alibi text COLLATE pg_catalog."default",
    approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status,
    CONSTRAINT "PK_case_suspect" PRIMARY KEY (suspect_id, case_id)
);

CREATE TABLE IF NOT EXISTS public.case_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    CONSTRAINT "PK_case_type" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    apartment_number integer,
    building_number character varying(30) COLLATE pg_catalog."default" NOT NULL,
    city character varying(30) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    father_name character varying(100) COLLATE pg_catalog."default",
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    region character varying(30) COLLATE pg_catalog."default" NOT NULL,
    registration_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    street character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_client" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detective
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    father_name character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    region character varying(30) COLLATE pg_catalog."default" NOT NULL,
    city character varying(30) COLLATE pg_catalog."default" NOT NULL,
    street character varying(50) COLLATE pg_catalog."default" NOT NULL,
    building_number character varying(30) COLLATE pg_catalog."default" NOT NULL,
    apartment_number integer,
    hire_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    salary numeric(10, 2) NOT NULL,
    personal_notes text COLLATE pg_catalog."default",
    status detective_status NOT NULL DEFAULT 'Активний(а)'::detective_status,
    CONSTRAINT "PK_detective" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.evidence
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type evidence_type NOT NULL,
    collection_date timestamp with time zone NOT NULL,
    region character varying(200) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Не вказано'::character varying,
    annotation character varying(200) COLLATE pg_catalog."default",
    purpose character varying(200) COLLATE pg_catalog."default",
    approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status,
    CONSTRAINT "PK_evidence" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    case_id integer NOT NULL,
    date_time timestamp with time zone NOT NULL,
    purpose character varying(255) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(10, 2) NOT NULL,
    annotation text COLLATE pg_catalog."default",
    approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status,
    CONSTRAINT "PK_expense" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.report
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    case_id integer NOT NULL,
    report_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    summary text COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status,
    CONSTRAINT "PK_report" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.suspect
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    father_name character varying(100) COLLATE pg_catalog."default",
    nickname character varying(50) COLLATE pg_catalog."default",
    phone_number character varying(20) COLLATE pg_catalog."default",
    date_of_birth date,
    region character varying(30) COLLATE pg_catalog."default",
    city character varying(30) COLLATE pg_catalog."default",
    street character varying(50) COLLATE pg_catalog."default",
    building_number character varying(30) COLLATE pg_catalog."default",
    apartment_number integer,
    height integer,
    weight integer,
    physical_description text COLLATE pg_catalog."default",
    prior_convictions text COLLATE pg_catalog."default",
    approval_status approval_status NOT NULL DEFAULT 'Чернетка'::approval_status,
    CONSTRAINT "PK_suspect" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."case"
    ADD CONSTRAINT "FK_case_case_type_id" FOREIGN KEY (case_type_id)
    REFERENCES public.case_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_case_case_type_id"
    ON public."case"(case_type_id);


ALTER TABLE IF EXISTS public."case"
    ADD CONSTRAINT "FK_case_client_id" FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_case_client_id"
    ON public."case"(client_id);


ALTER TABLE IF EXISTS public."case"
    ADD CONSTRAINT "FK_case_detective_id" FOREIGN KEY (detective_id)
    REFERENCES public.detective (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_case_detective_id"
    ON public."case"(detective_id);


ALTER TABLE IF EXISTS public.case_evidence
    ADD CONSTRAINT "FK_case_evidence_case_id" FOREIGN KEY (case_id)
    REFERENCES public."case" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_case_evidence_case_id"
    ON public.case_evidence(case_id);


ALTER TABLE IF EXISTS public.case_evidence
    ADD CONSTRAINT "FK_case_evidence_suspect_id" FOREIGN KEY (evidence_id)
    REFERENCES public.evidence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.case_suspect
    ADD CONSTRAINT "FK_case_suspect_case_id" FOREIGN KEY (case_id)
    REFERENCES public."case" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_case_suspect_case_id"
    ON public.case_suspect(case_id);


ALTER TABLE IF EXISTS public.case_suspect
    ADD CONSTRAINT "FK_case_suspect_suspect_id" FOREIGN KEY (suspect_id)
    REFERENCES public.suspect (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.expense
    ADD CONSTRAINT expense_case_id_fk FOREIGN KEY (case_id)
    REFERENCES public."case" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_expense_case_id"
    ON public.expense(case_id);


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT "FK_report_case_id" FOREIGN KEY (case_id)
    REFERENCES public."case" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_report_case_id"
    ON public.report(case_id);

END;